---
name: MariaDB for GitHub Actions
description: 
inputs: 
  mariadb-version:
    description: MariaDB version to be installed
    required: true
    default: 10.3
  db-user:
    description: Database user to be created
    required: true
  db-password:
    description: Password for the user
    required: true
  db-name: 
    description: Database to be created
    required: true
runs:
 using: node16
 main: action/index.js